train:
  batch_size: 256
  epochs: 20
  lr: 0.0005
  weight_decay: 0.0001
  num_workers: 4
  device_preference: cuda
  log_interval: 10
  output_dir: checkpoints/regnety_016
  amp: true
  label_smoothing: 0.1
  early_stopping:
    patience: 3